name: Deploy Example to Vercel

on:
  push:
    branches:
      - main
      - master
    paths:
      - "example/**" # Only trigger when example folder changes
  pull_request:
    branches:
      - main
      - master
    paths:
      - "example/**"
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0" # Specify your Flutter version
          channel: "stable"

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install root package dependencies
        run: flutter pub get

      - name: Install example dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Build Flutter Web App
        working-directory: ./example
        run: |
          flutter build web --release

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          cp -r example/build/web/* deploy/

      - name: Create vercel.json
        run: |
          cat > deployvercel.json << EOF
          {
            "version": 2,
            "routes": [
              {
                "src": "/(.*)",
                "dest": "/index.html"
              }
            ]
          }
          EOF

      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        working-directory: ./deploy
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel (Production)
        if: github.event_name == 'push'
        working-directory: ./deploy
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --yes --prod
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
